// <auto-generated />
namespace SC1605___Garage20.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DataTypeaddedtoDates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataTypeaddedtoDates));
        
        string IMigrationMetadata.Id
        {
            get { return "201607041132108_DataType added to Dates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
